name: Tests

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Build packages
        run: bun run build

      - name: Run tests with coverage
        run: bun test --coverage --coverage-reporter=lcov

      - name: Report coverage to PR
        if: github.event_name == 'pull_request'
        uses: zgosalvez/github-actions-report-lcov@v5
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 80
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
